modelpath: 'unet_z3_nc0_ns1.5-huberloss-gaussianfilter.pt'
train_h5: '/mnt/nvme2/iGlu_train_data/iglu_train_data_cropsize32_roisize6_stim_z3_filtered.h5'
batch_size: 64
learning_rate: 0.0001
lossfunction: 'L1'
num_epochs: 2
noise_center: 0
noise_scale: 1.5
gausian_filter: True
sigma_gausian_filter: 1.0